name: CI for Flask with Docker

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic test
      run: |
        echo "Testing Flask App"
        python -c "import app; assert app.hello() == 'Hello, Flask in Docker!'"

    - name: Build Docker image
      run: |
        docker build -t flask-docker-demo .

    # Optional: Push to Docker Hub (set secrets first)
    # - name: Log in to Docker Hub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Push image
    #   run: |
    #     docker tag flask-docker-demo yourdockerhub/flask-docker-demo:latest
    #     docker push yourdockerhub/flask-docker-demo:latest
